
- name: Installing Pre-Requisites - Docker
  apt:
    name:
      - ca-certificates
      - curl

- name: Creating keyrings directory if not exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Downloading Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: '0644'

- name: Adding Docker Repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable\n"
    owner: root
    group: root
    mode: '0644'

- name: Updating APT package index
  apt:
    update_cache: yes

- name: Installing docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

