- name: Creating configuration directories
  file:
    path: /opt/grafana/prometheus
    state: directory
    mode: '0755'

- name: Creating dashboards directory
  file:
    path: /opt/grafana/provisioning/dashboards
    state: directory
    mode: '0755'

- name: Creating datasources directory
  file:
    path: /opt/grafana/provisioning/datasources
    state: directory
    mode: '0755'

- name: Creating JSONs directory
  file:
    path: /opt/grafana/jsons
    state: directory
    mode: '0755'

- name: Copying Prometheus configuration file
  shell: envsubst < {{ ansible_pull_dir }}/server/config/prometheus.yml.template > /opt/grafana/prometheus/prometheus.yml

- name: Copying Dashboards configuration file
  copy:
    src: "{{ ansible_pull_dir }}/server/config/dashboards.yml"
    dest: /opt/grafana/provisioning/dashboards/dashboards.yml
    mode: '0644'
  
- name: Copying Default Dashboard JSON
  copy:
    src: "{{ ansible_pull_dir }}/server/config/default-dashboard.json"
    dest: /opt/grafana/jsons/default-dashboard.json
    mode: '0644'

- name: Copying Default Datasource
  copy:
    src: "{{ ansible_pull_dir }}/server/config/default-datasource.yml"
    dest: /opt/grafana/provisioning/datasources/datasource.yml
    mode: '0644'

- name: Copying Docker Compose file
  copy:
    src: "{{ ansible_pull_dir }}/server/config/docker-compose.yml"
    dest: /opt/grafana/docker-compose.yml
    mode: '0644'

- name: Creating env file for Docker Compose
  copy:
    dest: /opt/grafana/.env
    content: |
      grafana_admin_user={{ grafana_user }}
      grafana_admin_password={{ grafana_password }}
      name={{ app_name }}

- name: Starting Docker Compose Services
  shell: "cd /opt/grafana && docker compose up -d"