- name: Creating configuration directories
  file:
    path: /opt/grafana/prometheus
    state: directory
    mode: '0755'

- name: Copying Prometheus configuration file
  shell: envsubst < {{ ansible_pull_dir }}/server/config/prometheus.yml.template > /opt/grafana/prometheus/prometheus.yml

- name: Copying Docker Compose file
  copy:
    src: "{{ ansible_pull_dir }}/server/config/docker-compose.yml"
    dest: /opt/grafana/docker-compose.yml
    mode: '0644'

- name: Creating env file for Docker Compose
  copy:
    dest: /opt/grafana/.env
    content: |
      grafana_admin_user={{ grafana_user }}
      grafana_admin_password={{ grafana_password }}
      name={{ app_name }}

- name: Switching to Grafana directory
  shell: "cd /opt/grafana"

- name: Starting Docker Compose services
  shell: docker compose up -d