---
- name: Configuration playbook
  hosts: localhost
  gather_facts: yes
  vars:
    ansible_pull_dir: "/opt/bootstrap/ansible/ansible"
  tasks:
    - name: Distribution Info
      ansible.builtin.debug:
        msg: "Family: {{ ansible_os_family | lower }} ,Distribution: {{ ansible_distribution }}, Version: {{ ansible_distribution_version }}, Release: {{ ansible_distribution_release }}"

    - name: Insatlling Cloudflare Zero Trust Tunnel
      include_tasks: cloudflare.yml
      when: cloudflare == "true"

    - name: Installing Docker
      include_tasks: docker.yml
    
    - name: Setting up Grafana and Prometheus
      include_tasks: grafana.yml