---
- name: Configuration playbook
  hosts: localhost
  gather_facts: yes
  vars:
    ansible_pull_dir: "/opt/bootstrap/ansible/ansible"
  tasks:
    - name: Distribution Info
      ansible.builtin.debug:
        msg: "Family: {{ ansible_os_family | lower }} ,Distribution: {{ ansible_distribution }}, Version: {{ ansible_distribution_version }}, Release: {{ ansible_distribution_release }}"

    - name: Installing Docker
      include_tasks: ../docker.yml
    
    - name: Configuring Node Exporter
      include_tasks: node_exporter.yml